#!/usr/bin/env python3
keys = {
    "AppTitleSuffix": ("— Runews", "— Runews"),
    "Lang_Ru": ("RU", "RU"),
    "Lang_En": ("EN", "EN"),
    "Nav_Feed": ("Лента", "Feed"),
    "Nav_Saved": ("Избранное", "Saved"),
    "Nav_SectionPublicist": ("Публицистика", "Publishing"),
    "Nav_WriteArticle": ("Написать статью", "Write article"),
    "Nav_MyArticles": ("Мои статьи", "My articles"),
    "Nav_SectionModeration": ("Модерация", "Moderation"),
    "Nav_Queue": ("Очередь", "Queue"),
    "Nav_Reports": ("Жалобы", "Reports"),
    "Nav_SectionAdmin": ("Администрирование", "Administration"),
    "Nav_Rss": ("Настройка RSS", "RSS settings"),
    "Nav_Tags": ("Управление тегами", "Manage tags"),
    "Nav_Users": ("Пользователи", "Users"),
    "Nav_Search": ("Поиск", "Search"),
    "Nav_ThemeLight": ("Светлая тема", "Light theme"),
    "Nav_ThemeDark": ("Тёмная тема", "Dark theme"),
    "Nav_Login": ("Войти", "Sign in"),
    "Nav_SearchPlaceholder": ("Поиск новостей...", "Search news..."),
    "Nav_SearchNoResults": ("Ничего не найдено по запросу «{0}»", 'No results for "{0}"'),
    "Nav_SearchPressEnter": ("Нажмите Enter для поиска по запросу «{0}»", 'Press Enter to search for "{0}"'),
    "Nav_SearchStartTyping": ("Начните вводить запрос...", "Start typing your query..."),
    "Nav_HideMenu": ("Скрыть меню", "Hide menu"),
    "Nav_ShowMenu": ("Показать меню", "Show menu"),
    "Nav_HideToc": ("Скрыть содержание", "Hide table of contents"),
    "Nav_ShowToc": ("Показать содержание", "Show table of contents"),
    "Nav_Toc": ("Содержание", "Contents"),
    "Nav_DevBanner": ("Включен режим разработчика на сервере", "Development mode is enabled on the server"),
    "Common_Loading": ("Загрузка...", "Loading..."),
    "Common_Back": ("Назад", "Back"),
    "Common_Cancel": ("Отмена", "Cancel"),
    "Common_Close": ("Закрыть", "Close"),
    "Common_Save": ("Сохранить", "Save"),
    "Common_Delete": ("Удалить", "Delete"),
    "Common_Add": ("Добавить", "Add"),
    "Common_Send": ("Отправить", "Send"),
    "Common_All": ("Все", "All"),
    "Common_Total": ("Всего: {0}", "Total: {0}"),
    "Common_Error": ("Ошибка.", "Error."),
    "Common_ErrorSave": ("Ошибка при сохранении.", "Failed to save."),
    "Common_ErrorDelete": ("Ошибка при удалении.", "Failed to delete."),
    "Common_Name": ("Название", "Name"),
    "Common_Url": ("URL", "URL"),
    "Common_Date": ("Дата", "Date"),
    "Common_Actions": ("Действия", "Actions"),
    "Common_MoveUp": ("Выше", "Move up"),
    "Common_MoveDown": ("Ниже", "Move down"),
    "Status_Draft": ("Черновик", "Draft"),
    "Status_Pending": ("На проверке", "Pending review"),
    "Status_Published": ("Опубликована", "Published"),
    "Status_Rejected": ("Отклонена", "Rejected"),
    "Role_Admin": ("Администратор", "Admin"),
    "Role_Moderator": ("Модератор", "Moderator"),
    "Role_Publicist": ("Публицист", "Publicist"),
    "Role_User": ("Пользователь", "User"),
    "Auth_PageLogin": ("Вход — Runews", "Sign in — Runews"),
    "Auth_PageRegister": ("Регистрация — Runews", "Register — Runews"),
    "Auth_LoginTitle": ("Вход в аккаунт", "Sign in"),
    "Auth_RegisterTitle": ("Создать аккаунт", "Create account"),
    "Auth_ForgotTitle": ("Восстановление пароля", "Password recovery"),
    "Auth_ForgotSubtitle": ("Введите email — мы отправим ссылку для сброса пароля.", "Enter your email and we will send a reset link."),
    "Auth_ResetTitle": ("Новый пароль", "New password"),
    "Auth_Email": ("Email", "Email"),
    "Auth_Password": ("Пароль", "Password"),
    "Auth_PasswordConfirm": ("Повторите пароль", "Confirm password"),
    "Auth_PasswordMin6": ("Минимум 6 символов", "At least 6 characters"),
    "Auth_PasswordEnter": ("Введите пароль", "Enter password"),
    "Auth_LoginBtn": ("Войти", "Sign in"),
    "Auth_RegisterBtn": ("Зарегистрироваться", "Register"),
    "Auth_ForgotBtn": ("Отправить ссылку", "Send link"),
    "Auth_ResetBtn": ("Сохранить пароль", "Save password"),
    "Auth_HaveAccount": ("Уже есть аккаунт? Войти", "Already have an account? Sign in"),
    "Auth_ForgotLink": ("Забыли пароль?", "Forgot password?"),
    "Auth_CreateAccount": ("Создать аккаунт", "Create account"),
    "Auth_EmailNotConfirmed": ("Подтвердите email перед входом. Проверьте почту.", "Confirm your email before signing in. Check your inbox."),
    "Auth_EmailConfirmed": ("Email подтверждён! Теперь можно войти.", "Email confirmed! You can sign in now."),
    "Auth_ErrorEmail": ("Введите корректный email (например: you@example.com)", "Enter a valid email (e.g. you@example.com)"),
    "Auth_ErrorPasswordEmpty": ("Пароль не может быть пустым", "Password cannot be empty"),
    "Auth_ErrorPasswordMin6": ("Пароль должен содержать минимум 6 символов", "Password must be at least 6 characters"),
    "Auth_ErrorPasswordMismatch": ("Пароли не совпадают", "Passwords do not match"),
    "Auth_ErrorFillAll": ("Заполните все поля.", "Fill in all fields."),
    "Auth_ConfirmPending": ("Подтверждаем ваш email...", "Confirming your email..."),
    "Auth_ConfirmSuccess": ("Email подтверждён!", "Email confirmed!"),
    "Auth_ConfirmRedirect": ("Перенаправляем на главную страницу...", "Redirecting to home..."),
    "Auth_ConfirmInvalid": ("Ссылка недействительна", "Invalid link"),
    "Auth_ConfirmInvalidHint": ("Ссылка устарела или уже была использована.", "The link has expired or was already used."),
    "Auth_GoHome": ("На главную", "Go to home"),
    "Home_Title": ("Лента — Runews", "Feed — Runews"),
    "Home_ForYou": ("Для вас", "For you"),
    "Home_Feed": ("Лента новостей", "News feed"),
    "Home_SortNewest": ("Новые", "Newest"),
    "Home_SortOldest": ("Старые", "Oldest"),
    "Home_SortPopular": ("Популярные", "Popular"),
    "Home_RecEnabled": ("Лента персонализирована на основе ваших интересов", "Feed is personalized based on your interests"),
    "Home_RecDisabled": ("Персональные рекомендации отключены — показана общая лента", "Personal recommendations are off — showing the public feed"),
    "Home_RecDisable": ("Отключить функцию", "Turn off"),
    "Home_RecEnable": ("Включить функцию", "Turn on"),
    "Home_AllSources": ("Все источники", "All sources"),
    "Home_AuthorsOnly": ("Авторские", "By authors"),
    "Home_Empty": ("Статей не найдено. Попробуйте изменить фильтры.", "No articles found. Try changing filters."),
    "Home_Recommended": ("Рекомендовано", "Recommended"),
    "Home_Save": ("Сохранить", "Save"),
    "Home_Unsave": ("Убрать из избранного", "Remove from saved"),
    "Home_AccountDeleted": ("Аккаунт удалён.", "Account deleted."),
    "Home_AccountDeletedThanks": ("Спасибо, что были с нами.", "Thank you for being with us."),
    "Home_EmailConfirmed": ("Email успешно подтверждён.", "Email confirmed successfully."),
    "Home_EmailConfirmedLogin": ("Теперь вы можете войти в аккаунт.", "You can sign in now."),
    "Saved_Title": ("Избранное — Runews", "Saved — Runews"),
    "Saved_Heading": ("Избранное", "Saved"),
    "Saved_Count": ("{0} статей", "{0} articles"),
    "Saved_Empty": ("Вы ещё ничего не сохранили.", "You have not saved anything yet."),
    "Saved_BackToFeed": ("← В ленту", "← Back to feed"),
    "Article_NotFound": ("Статья не найдена или была удалена.", "Article not found or was deleted."),
    "Article_BackToFeed": ("← Вернуться в ленту", "← Back to feed"),
    "Article_Comments": ("Комментарии", "Comments"),
    "Article_CommentPlaceholder": ("Напишите комментарий...", "Write a comment..."),
    "Article_CommentSubmit": ("Отправить", "Send"),
    "Article_LoginToComment": ("Войдите, чтобы оставить комментарий.", "Sign in to leave a comment."),
    "Article_CommentsEmpty": ("Комментариев пока нет. Будьте первым!", "No comments yet. Be the first!"),
    "Article_Reply": ("Ответить", "Reply"),
    "Article_Report": ("Пожаловаться", "Report"),
    "Article_ReportTitle": ("Пожаловаться на статью", "Report article"),
    "Article_ReportSent": ("Жалоба отправлена. Спасибо!", "Report submitted. Thank you!"),
    "Mod_QueueTitle": ("Очередь модерации — Runews", "Moderation queue — Runews"),
    "Mod_ReviewTitle": ("Проверка статьи — Runews", "Article review — Runews"),
    "Mod_ReportsTitle": ("Жалобы — Runews", "Reports — Runews"),
    "Mod_QueueHeading": ("Очередь модерации", "Moderation queue"),
    "Mod_OnReview": ("На проверке: {0}", "Pending: {0}"),
    "Mod_QueueEmpty": ("Очередь пуста — все статьи проверены.", "Queue is empty — all articles reviewed."),
    "Mod_Review": ("Проверить", "Review"),
    "Mod_Approve": ("Одобрить", "Approve"),
    "Mod_Reject": ("Отклонить", "Reject"),
    "Mod_RejectCount": ("Отклонить ({0})", "Reject ({0})"),
    "Mod_BackQueue": ("Очередь", "Queue"),
    "Mod_NotInQueue": ("Статья не найдена в очереди.", "Article not found in queue."),
    "Mod_ReturnQueue": ("Вернуться в очередь", "Back to queue"),
    "Mod_SourceText": ("Исходный текст (выделяйте здесь)", "Source text (select here)"),
    "Mod_AddNote": ("Добавить замечание по выделению", "Add note from selection"),
    "Mod_Preview": ("Предпросмотр", "Preview"),
    "Mod_Notes": ("Замечания ({0})", "Notes ({0})"),
    "Mod_NotesEmpty": ("Выделите фрагмент слева и добавьте хотя бы одно замечание перед отклонением.", "Select text on the left and add at least one note before rejecting."),
    "Mod_Summary": ("Общий комментарий (необязательно)", "General comment (optional)"),
    "Mod_SummaryPlaceholder": ("Краткий итог для автора", "Brief summary for the author"),
    "Mod_NoteTitle": ("Замечание к фрагменту", "Note for excerpt"),
    "Mod_NoteReason": ("Причина (обязательно)", "Reason (required)"),
    "Mod_NoteReasonMin": ("Укажите причину (минимум 3 символа).", "Enter a reason (at least 3 characters)."),
    "Mod_SelectFragment": ("Выделите фрагмент в левой панели (минимум 3 символа).", "Select text in the left panel (at least 3 characters)."),
    "Mod_DuplicateFragment": ("Этот фрагмент уже добавлен.", "This excerpt is already added."),
    "Mod_AddNoteBeforeReject": ("Добавьте хотя бы одно замечание.", "Add at least one note."),
    "Mod_Published": ("Статья опубликована.", "Article published."),
    "Mod_ErrorApprove": ("Ошибка при одобрении.", "Failed to approve."),
    "Mod_ErrorReject": ("Ошибка при отклонении.", "Failed to reject."),
    "Mod_ReportsHeading": ("Жалобы", "Reports"),
    "Mod_ReportsActive": ("Активных: {0}", "Active: {0}"),
    "Mod_ReportsEmpty": ("Жалоб нет.", "No reports."),
    "Editor_CreateTitle": ("Написать статью — Runews", "Write article — Runews"),
    "Editor_EditTitle": ("Редактировать статью — Runews", "Edit article — Runews"),
    "Editor_Write": ("Написать статью", "Write article"),
    "Editor_Edit": ("Редактировать статью", "Edit article"),
    "Editor_Preview": ("Предпросмотр", "Preview"),
    "Editor_EditorMode": ("Редактор", "Editor"),
    "Editor_Draft": ("Черновик", "Draft"),
    "Editor_ModeratorNotes": ("Замечания модератора", "Moderator notes"),
    "Editor_HighlightHint": ("Подсветка фрагментов отображается в режиме «Предпросмотр».", "Excerpt highlights appear in Preview mode."),
    "Editor_TitlePlaceholder": ("Заголовок статьи...", "Article title..."),
    "Editor_ContentPlaceholder": ("Начните писать статью в формате Markdown...", "Start writing in Markdown..."),
    "Editor_PreviewEmpty": ("Нет содержимого для предпросмотра.", "Nothing to preview."),
    "Editor_ErrorTitle": ("Введите заголовок.", "Enter a title."),
    "Editor_ErrorContent": ("Статья не может быть пустой.", "Article cannot be empty."),
    "Editor_Saved": ("Статья обновлена и отправлена на модерацию.", "Article updated and sent for review."),
    "Editor_Created": ("Статья создана и отправлена на модерацию.", "Article created and sent for review."),
    "Editor_DraftSaved": ("Черновик сохранён.", "Draft saved."),
    "Editor_MyArticles": ("Мои статьи — Runews", "My articles — Runews"),
    "Editor_MyArticlesHeading": ("Мои статьи", "My articles"),
    "Editor_NoArticles": ("Статей нет.", "No articles yet."),
    "Editor_WriteFirst": ("Написать первую?", "Write the first one?"),
    "Editor_RejectionTitle": ("Причина отклонения", "Rejection reason"),
    "Editor_RejectionUnknown": ("Причина не указана", "No reason provided"),
    "Editor_ModeratorNotesTooltip": ("Замечания модератора", "Moderator notes"),
    "Editor_DeleteTitle": ("Удалить статью?", "Delete article?"),
    "Editor_DeleteBody": ("«{0}» будет удалена безвозвратно.", '"{0}" will be deleted permanently.'),
    "Footer_Description": ("Runews — новостной агрегатор нового поколения. Собираем актуальные новости из проверенных источников и персонализируем ленту под ваши интересы.", "Runews is a next-generation news aggregator. We collect news from trusted sources and personalize your feed."),
    "Footer_Company": ("Компания", "Company"),
    "Footer_About": ("О нас", "About us"),
    "Footer_Social": ("Мы в соцсетях", "Follow us"),
    "Footer_Copyright": ("© {0} Runews. Все права защищены.", "© {0} Runews. All rights reserved."),
    "Footer_Terms": ("Пользовательское соглашение", "Terms of use"),
    "Footer_Edu": ("Проект создан в учебных целях", "Educational project"),
    "Editor_DraftRestored": ("Черновик восстановлен.", "Draft restored."),
    "Editor_Discard": ("Отменить", "Discard"),
    "Editor_ColTitle": ("Заголовок", "Title"),
    "Editor_ColTags": ("Теги", "Tags"),
    "Editor_ColStatus": ("Статус", "Status"),
    "Editor_ColDate": ("Дата", "Date"),
    "Editor_ColLikes": ("Лайки", "Likes"),
    "Editor_ColActions": ("Действия", "Actions"),
    "Editor_Open": ("Открыть", "Open"),
    "Editor_EditBtn": ("Редактировать", "Edit"),
    "Editor_DeleteBody": ("«{0}» будет удалена безвозвратно.", '"{0}" will be deleted permanently.'),
    "Mod_ReportsColType": ("Тип", "Type"),
    "Mod_ReportsColArticle": ("Статья", "Article"),
    "Mod_ReportsColFrom": ("От кого", "From"),
    "Mod_ReportsColDescription": ("Описание", "Description"),
    "Admin_UsersTitle": ("Управление пользователями", "User management"),
    "Admin_UsersPageTitle": ("Пользователи — Runews", "Users — Runews"),
    "Article_CommentsTitle": ("Комментарии", "Comments"),
    "Article_NotFoundTitle": ("Статья — Runews", "Article — Runews"),
    "Auth_Username": ("Имя пользователя", "Username"),
    "Auth_ForgotSuccess": ("Если аккаунт с адресом {0} существует, письмо с инструкцией уже в пути.", "If an account with {0} exists, we have sent instructions."),
    "Auth_ForgotNotFound": ("Аккаунт с таким email не найден.", "No account found with this email."),
    "Auth_ForgotEnterEmail": ("Введите email.", "Enter your email."),
    "Auth_BackToLogin": ("Вернуться ко входу", "Back to sign in"),
    "Auth_RegisterEmailSent": ("Письмо с подтверждением отправлено на", "Confirmation email sent to"),
    "Auth_RegisterEmailSentHint": ("Перейдите по ссылке в письме, чтобы активировать аккаунт", "Follow the link in the email to activate your account"),
    "Auth_AvatarColor": ("Цвет аватара", "Avatar color"),
    "Auth_AvatarPreview": ("Предпросмотр", "Preview"),
    "Auth_AvatarUploadOptional": ("Загрузить аватар (необязательно)", "Upload avatar (optional)"),
    "Auth_ErrorRegisterConflict": ("Пользователь с таким email уже существует.", "A user with this email already exists."),
    "Auth_ErrorRegisterGeneric": ("Не удалось зарегистрироваться. Попробуйте позже.", "Registration failed. Try again later."),
    "Profile_PageTitle": ("Профиль — Runews", "Profile — Runews"),
    "Profile_UploadAvatar": ("Загрузить аватар", "Upload avatar"),
    "Profile_DeletePhoto": ("Удалить фото", "Remove photo"),
    "Profile_EditSection": ("Редактировать профиль", "Edit profile"),
    "Profile_NewUsernamePlaceholder": ("Новое имя", "New username"),
    "Profile_PasswordOptionalHint": ("(оставьте пустым, чтобы не менять)", "(leave empty to keep unchanged)"),
    "Profile_NewPassword": ("Новый пароль", "New password"),
    "Profile_ConfirmPassword": ("Подтвердите пароль", "Confirm password"),
    "Profile_RepeatPasswordPlaceholder": ("Повторите новый пароль", "Repeat new password"),
    "Profile_AvatarColorNoPhoto": ("(если нет фото)", "(when no photo)"),
    "Profile_Logout": ("Выйти", "Log out"),
    "Profile_DeleteAccount": ("Удалить профиль", "Delete account"),
    "Profile_DeleteTitle": ("Удалить аккаунт?", "Delete account?"),
    "Profile_DeleteBody": ("Это действие необратимо. Все ваши данные, комментарии и сохранённые статьи будут удалены безвозвратно.", "This cannot be undone. All your data, comments, and saved articles will be permanently deleted."),
    "Profile_DeleteConfirm": ("Да, удалить", "Yes, delete"),
    "Profile_SavedSuccess": ("Профиль успешно обновлён.", "Profile updated successfully."),
    "Profile_ConfirmRequired": ("Подтверждение пароля обязательно", "Password confirmation is required"),
    "Profile_FileTooLarge": ("Файл не должен превышать 5 МБ.", "File must not exceed 5 MB."),
    "Editor_CoverLink": ("Обложка (ссылка)", "Cover (link)"),
    "Editor_Or": ("или", "or"),
    "Editor_Upload": ("Загрузить", "Upload"),
    "Editor_GuideLink": ("Инструкция к редактору", "Editor guide"),
    "Editor_RulesLink": ("Правила публикации", "Publishing rules"),
    "Editor_Tags": ("Теги:", "Tags:"),
    "Editor_TagSearch": ("Поиск:", "Search:"),
    "Editor_TagSearchPlaceholder": ("Введите тег для поиска или создания", "Enter a tag to search or create"),
    "Editor_CreateTag": ("Создать тег", "Create tag"),
    "Editor_ErrorCreateTag": ("Не удалось создать тег.", "Failed to create tag."),
    "Editor_CoverTooLarge": ("Файл не должен превышать 10 МБ.", "File must not exceed 10 MB."),
    "Guide_PageTitle": ("Инструкция к редактору — Runews", "Editor guide — Runews"),
    "Guide_BackToEditor": ("к редактору", "to editor"),
    "Guide_Title": ("Инструкция к редактору статей", "Article editor guide"),
    "Guide_Subtitle": ("Редактор использует формат Markdown — простой язык разметки текста. Ниже описаны все доступные элементы.", "The editor uses Markdown — a simple markup language. All available elements are listed below."),
    "Guide_Hotkeys": ("Горячие клавиши", "Keyboard shortcuts"),
    "Guide_HotkeyBold": ("Жирный текст", "Bold text"),
    "Guide_HotkeyItalic": ("Курсив", "Italic"),
    "Guide_HotkeyLink": ("Вставить ссылку", "Insert link"),
    "Guide_Headings": ("Заголовки", "Headings"),
    "Guide_H1Code": ("# Заголовок 1", "# Heading 1"),
    "Guide_H1Desc": ("Большой заголовок", "Large heading"),
    "Guide_H2Code": ("## Заголовок 2", "## Heading 2"),
    "Guide_H2Desc": ("Средний заголовок", "Medium heading"),
    "Guide_H3Code": ("### Заголовок 3", "### Heading 3"),
    "Guide_H3Desc": ("Малый заголовок", "Small heading"),
    "Guide_Formatting": ("Форматирование текста", "Text formatting"),
    "Guide_BoldCode": ("**жирный**", "**bold**"),
    "Guide_BoldSample": ("жирный", "bold"),
    "Guide_ItalicCode": ("*курсив*", "*italic*"),
    "Guide_ItalicSample": ("курсив", "italic"),
    "Guide_StrikeCode": ("~~зачёркнутый~~", "~~strikethrough~~"),
    "Guide_StrikeSample": ("зачёркнутый", "strikethrough"),
    "Guide_InlineCode": ("`код`", "`code`"),
    "Guide_InlineCodeDesc": ("встроенный код", "inline code"),
    "Guide_Lists": ("Списки", "Lists"),
    "Guide_BulletCode": ("- пункт", "- item"),
    "Guide_BulletDesc": ("Маркированный список", "Bullet list"),
    "Guide_NumberCode": ("1. пункт", "1. item"),
    "Guide_NumberDesc": ("Нумерованный список", "Numbered list"),
    "Guide_LinksImages": ("Ссылки и изображения", "Links and images"),
    "Guide_LinkCode": ("[текст](url)", "[text](url)"),
    "Guide_LinkDesc": ("Гиперссылка", "Hyperlink"),
    "Guide_ImageCode": ("![описание](url)", "![alt](url)"),
    "Guide_ImageDesc": ("Изображение", "Image"),
    "Guide_Other": ("Прочее", "Other"),
    "Guide_QuoteCode": ("&gt; текст", "&gt; text"),
    "Guide_QuoteDesc": ("Цитата", "Quote"),
    "Guide_CodeBlockDesc": ("Блок кода", "Code block"),
    "Guide_HrDesc": ("Горизонтальная линия", "Horizontal rule"),
    "Guide_Note": ("После написания статьи нажмите {0} — статья будет отправлена на модерацию и опубликована после проверки.", "When finished, click {0} — the article will be sent for review and published after approval."),
    "Rules_PageTitle": ("Правила публикации — Runews", "Publishing rules — Runews"),
    "Rules_Title": ("Правила публикации статей", "Article publishing rules"),
    "Rules_Subtitle": ("Перед публикацией убедитесь, что ваша статья соответствует требованиям сообщества. Нарушение правил приведёт к отклонению материала или блокировке аккаунта.", "Before publishing, make sure your article meets community standards. Violations may result in rejection or account suspension."),
    "Rules_GeneralTitle": ("Общие требования", "General requirements"),
    "Rules_General1": ("Статья должна быть написана на русском или английском языке.", "Articles must be written in Russian or English."),
    "Rules_General2": ("Минимальный объём — 300 символов. Слишком короткие материалы не несут ценности для читателей.", "Minimum length is 300 characters. Very short posts add little value for readers."),
    "Rules_General3": ("Заголовок должен точно отражать содержание статьи и не вводить читателя в заблуждение.", "The title must accurately reflect the content and must not mislead readers."),
    "Rules_General4": ("Текст должен быть грамотным, структурированным и читаемым.", "Text must be well-written, structured, and easy to read."),
    "Rules_General5": ("Один автор не может публиковать более 5 статей в сутки.", "An author may publish no more than 5 articles per day."),
    "Rules_ForbiddenTitle": ("Запрещённый контент", "Prohibited content"),
    "Rules_Forbidden1": ("Дезинформация и фейки — публикация заведомо ложных сведений, непроверенных слухов или манипулятивных материалов.", "Misinformation and fakes — knowingly false claims, unverified rumors, or manipulative content."),
    "Rules_Forbidden2": ("Разжигание ненависти — материалы, направленные против людей по признаку расы, национальности, религии, пола или сексуальной ориентации.", "Hate speech — content targeting people based on race, nationality, religion, gender, or sexual orientation."),
    "Rules_Forbidden3": ("Спам и реклама — коммерческие объявления, партнёрские ссылки без пометки, массовые однотипные публикации.", "Spam and ads — commercial posts, undisclosed affiliate links, or mass duplicate publishing."),
    "Rules_Forbidden4": ("Насилие и жестокость — детальные описания или изображения насилия, контент 18+.", "Violence and cruelty — graphic descriptions or images of violence, 18+ content."),
    "Rules_Forbidden5": ("Нарушение авторских прав — полное копирование чужих материалов без указания источника и разрешения автора.", "Copyright infringement — copying others' work without attribution and permission."),
    "Rules_Forbidden6": ("Личные данные — публикация персональных данных третьих лиц без их согласия.", "Personal data — publishing third parties' personal information without consent."),
    "Rules_FormatTitle": ("Требования к оформлению", "Formatting requirements"),
    "Rules_Format1": ("Используйте заголовки (H2, H3) для структурирования длинных материалов.", "Use headings (H2, H3) to structure long articles."),
    "Rules_Format2": ("Обложка статьи должна соответствовать теме и не содержать текст, перекрывающий изображение.", "The cover image must match the topic and should not have text covering the image."),
    "Rules_Format3": ("Ссылки на внешние источники должны вести на авторитетные ресурсы.", "External links should point to reputable sources."),
    "Rules_Format4": ("Цитаты из других источников оформляйте через блок цитирования (&gt; текст) с указанием автора.", "Quote other sources using block quotes (&gt; text) with attribution."),
    "Rules_Format5": ("Теги должны точно соответствовать тематике статьи — не добавляйте нерелевантные теги для привлечения трафика.", "Tags must match the article topic — do not add irrelevant tags for traffic."),
    "Rules_ModerationTitle": ("Процесс модерации", "Moderation process"),
    "Rules_Step1Title": ("Отправка на проверку", "Submit for review"),
    "Rules_Step1Text": ("После нажатия «{0}» статья получает статус «{1}» и становится видна только вам.", "After clicking \"{0}\", the article is marked \"{1}\" and is visible only to you."),
    "Rules_Step2Title": ("Проверка модератором", "Moderator review"),
    "Rules_Step2Text": ("Модератор проверяет соответствие правилам. Обычно это занимает до 24 часов.", "A moderator checks compliance with the rules. This usually takes up to 24 hours."),
    "Rules_Step3Title": ("Результат", "Outcome"),
    "Rules_Step3Text": ("Статья получает статус «{0}» или «{1}» с указанием причины.", "The article is marked \"{0}\" or \"{1}\" with a reason."),
    "Rules_ConsequencesTitle": ("Последствия нарушений", "Consequences of violations"),
    "Rules_Consequence1Title": ("Первое нарушение", "First violation"),
    "Rules_Consequence1Text": ("Статья отклоняется с объяснением причины.", "The article is rejected with an explanation."),
    "Rules_Consequence2Title": ("Систематические нарушения", "Repeated violations"),
    "Rules_Consequence2Text": ("Временная блокировка возможности публикации.", "Temporary suspension of publishing rights."),
    "Rules_Consequence3Title": ("Грубые нарушения", "Serious violations"),
    "Rules_Consequence3Text": ("Постоянная блокировка аккаунта без возможности восстановления.", "Permanent account ban without recovery."),
    "Rules_AppealNote": ("Если вы считаете, что ваша статья была отклонена ошибочно — свяжитесь с командой модерации. Мы рассмотрим апелляцию в течение 48 часов.", "If you believe your article was rejected by mistake, contact the moderation team. We will review appeals within 48 hours."),
}

HEADER = """<?xml version="1.0" encoding="utf-8"?>
<root>
  <resheader name="resmimetype"><value>text/microsoft-resx</value></resheader>
  <resheader name="version"><value>2.0</value></resheader>
  <resheader name="reader"><value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value></resheader>
  <resheader name="writer"><value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value></resheader>
"""

def esc(s: str) -> str:
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

def write_resx(path: str, idx: int) -> None:
    lines = [HEADER]
    for k in sorted(keys):
        lines.append(f'  <data name="{k}" xml:space="preserve"><value>{esc(keys[k][idx])}</value></data>')
    lines.append("</root>")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

base = "c:/directory-git/Coursework/CatshrediasNews.Client/Resources"
write_resx(f"{base}/SharedResources.resx", 0)
write_resx(f"{base}/SharedResources.en.resx", 1)
print(len(keys), "keys")
